---

- name: Ensuring git directory exists
  become: yes
  become_user: vagrant
  file:
    path: /home/vagrant/git/packages
    state: directory
    mode: '0755'

- name: Downloading Sublist3r
  become: yes
  become_user: vagrant
  git:
    repo: https://github.com/aboul3la/Sublist3r.git
    dest: /home/vagrant/git/packages/Sublist3r

- name: Installing Sublist3r dependencies
  become: yes
  become_user: vagrant
  pip:
    requirements: /home/vagrant/git/packages/Sublist3r/requirements.txt
    virtualenv: /home/vagrant/git/packages/Sublist3r/venv
    virtualenv_command: python3 -m venv