---

- name: Remove default virtualbox-guest-nox
  pacman:
    name: virtualbox-guest-utils-nox
    state: absent

- name: Install xorg
  pacman:
    name:
      - virtualbox-guest-utils
      - xorg-server
      - xorg-server-common
      - xorg-xauth
      - mesa
    state: present

- name: Install xorg keyboard settings
  become: true
  copy:
    src: 00-keyboard.conf
    dest: /etc/X11/xorg.conf.d/00-keyboard.conf
    owner: root
    group: root
    mode: "0644"

#- name: Install xorg debug packages
#  pacman:
#    name:
#      - xorg-twm
#      - xterm
#      - xorg-xclock
#      - xorg-xinit
