---

- name: Install Gnome & Virtualbox Guest additions
  pacman:
    name:
      - gnome
      - gnome-tweaks
      - gdm
    state: present

- name: Install Ubuntu Fonts
  pacman:
    name: ttf-ubuntu-font-family
    state: present

- name: Install Arc Theme
  pacman:
    name: arc-gtk-theme
    state: present

- name: Copy GDM config file to use Xorg
  copy:
    src: custom.conf
    dest: /etc/gdm/custom.conf
    owner: root
    group: root
    mode: '0644'

- name: enable GDM
  systemd:
    name: gdm
    enabled: yes

- include: theme.yml
  become: yes
  become_user: vagrant