---

- name: Install zsh
  pacman:
    name:
      - zsh
      - zsh-completions
      - zsh-autosuggestions
    state: present

- name: Set default shell to zsh for vagrant user
  command: chsh -s /bin/zsh vagrant

- name: Download oh-my-zsh
  become: yes
  become_user: vagrant
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/ohmyzsh_install.sh
    mode: '0755'

- name: Install oh-my-zsh
  become: yes
  become_user: vagrant
  command: /tmp/ohmyzsh_install.sh
  args:
    chdir: /home/vagrant
  ignore_errors: yes

- name: Install Powerline Fonts for Spaceship
  pacman:
    name: powerline-fonts
    state: present

- name: Download Spaceship
  become: yes
  become_user: vagrant
  git:
    repo: https://github.com/denysdovhan/spaceship-prompt.git
    dest: /home/vagrant/git/packages/spaceship-prompt

- name: Install Spaceship
  file:
    src: /home/vagrant/git/packages/spaceship-prompt/spaceship.zsh-theme
    dest: /home/vagrant/.oh-my-zsh/custom/themes/spaceship.zsh-theme
    owner: vagrant
    group: vagrant
    state: link
