---

- name: Install zsh
  pacman:
    name:
      - zsh
      - zsh-completions
      - zsh-autosuggestions
    state: present

- name: Set default shell to zsh for vagrant user
  command: chsh -s /bin/zsh vagrant

- name: Download oh-my-zsh
  become: yes
  become_user: vagrant
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/ohmyzsh_install.sh
    mode: '0755'

- name: Install oh-my-zsh
  become: yes
  become_user: vagrant
  command: /tmp/ohmyzsh_install.sh
  args:
    chdir: /home/vagrant
  ignore_errors: yes

- name: Ensure aur directory exists for user
  become: yes
  become_user: vagrant
  file:
    path: /home/vagrant/aur
    state: directory

- name: Clone powerline fonts AUR repo
  become: yes
  become_user: vagrant
  git:
    repo: https://aur.archlinux.org/powerline-fonts-git.git
    dest: /home/vagrant/aur/powerline-fonts-git

- name: Install powerline fonts
  become: yes
  become_user: vagrant
  command: makepkg --noconfirm -si
  args:
    chdir: /home/vagrant/aur/powerline-fonts-git

- name: Git checkout nerd-fonts
  become: yes
  become_user: vagrant
  git:
    repo: 'https://github.com/ryanoasis/nerd-fonts.git'
    dest: /home/vagrant/git/packages/nerd-fonts
    depth: 1

- name: Install nerd-fonts
  become: yes
  become_user: vagrant
  command: /home/vagrant/git/packages/nerd-fonts/install.sh

- name: Ensures go dir exists
  file:
    path: /home/vagrant/go
    state: directory
    owner: vagrant
    group: vagrant

- name: Download Spaceship
  become: yes
  become_user: vagrant
  git:
    repo: https://github.com/denysdovhan/spaceship-prompt.git
    dest: /home/vagrant/git/packages/spaceship-prompt
    depth: 1

- name: Install Spaceship
  file:
    src: /home/vagrant/git/packages/spaceship-prompt/spaceship.zsh-theme
    dest: /home/vagrant/.oh-my-zsh/custom/themes/spaceship.zsh-theme
    owner: vagrant
    group: vagrant
    state: link
