---

- name: Ensure packages directory exists for user
  become: yes
  become_user: vagrant
  file:
    path: /home/vagrant/git/packages
    state: directory

- name: clone asdf from github
  become: yes
  become_user: vagrant
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: /home/vagrant/git/packages/asdf
    depth: 1

- name: Create symbolic link to asdf
  file:
    src: /home/vagrant/git/packages/asdf
    dest: /home/vagrant/.asdf
    owner: vagrant
    group: vagrant
    state: link

- name: Install Terraform through asdf
  become: yes
  become_user: vagrant
  command: /home/vagrant/.asdf/bin/asdf plugin-add terraform https://github.com/Banno/asdf-hashicorp.git
