---

- name: Ensure aur directory exists for user
  become: yes
  become_user: vagrant
  file:
    path: /home/vagrant/aur
    state: directory

- name: Clone onesixtyone AUR repo
  become: yes
  become_user: vagrant
  git:
    repo: https://aur.archlinux.org/onesixtyone-git.git
    dest: /home/vagrant/aur/onesixtyone

- name: Install onesixtyone
  become: yes
  become_user: vagrant
  command: makepkg --noconfirm -si
  args:
    chdir: /home/vagrant/aur/onesixtyone
