---

- name: Ensure packages directory exists for user
  become: yes
  become_user: vagrant
  file:
    path: /home/vagrant/git/packages
    state: directory

- name: Clone SecLists repo
  become: yes
  become_user: vagrant
  git:
    repo: https://github.com/danielmiessler/SecLists.git
    dest: /home/vagrant/git/packages/seclists
