---

- name: Ensure aur directory exists for user
  become: yes
  become_user: vagrant
  file:
    path: /home/vagrant/aur
    state: directory

- name: Clone yay AUR helper
  become: yes
  become_user: vagrant
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: /home/vagrant/aur/yay

- name: Install yay
  become: yes
  become_user: vagrant
  command: makepkg --noconfirm -si
  args:
    chdir: /home/vagrant/aur/yay
