---

- name: Ensure iptables is installed
  pacman:
    name: iptables
    state: present

- name: Add ipv4 firewall config
  copy:
    src: iptables.rules
    dest: /etc/iptables/iptables.rules

- name: Add ipv6 firewall config
  copy:
    src: ip6tables.rules
    dest: /etc/iptables/ip6tables.rules

- name: Enable and start iptables
  service:
    name: iptables.service
    enabled: yes
    state: stopped

- name: Enable and start ip6tables
  service:
    name: ip6tables.service
    enabled: yes
    state: stopped
