---

- name: Installing python
  pacman:
    name:
    - python
    - python-pip
    - python-virtualenv
    - python-setuptools
    state: present

- name: Installing python docker
  pip:
    name: docker

- name: Installing python pyyaml
  pip:
    name: PyYAML

- name: Download ELK Docker-compose files
  become: yes
  become_user: vagrant
  git:
    repo: https://github.com/deviantony/docker-elk.git
    dest: /home/vagrant/packages/docker-elk

- name: Ensure docker is running
  service:
    name: docker
    state: started

- name: Start ELK services
  docker_compose:
    project_src: /home/vagrant/packages/docker-elk
