---

- name: Install Display Manager
  pacman:
    name:
      - lightdm
      - lightdm-gtk-greeter
    state: present

- name: Install i3
  pacman:
    name:
      - i3-gaps
      - i3status
      - i3lock
    state: present

- name: Install Fonts
  pacman:
    name:
      - noto-fonts
      - ttf-ubuntu-font-family
      - ttf-dejavu
      - ttf-freefont
      - ttf-liberation
      - ttf-droid
      - ttf-inconsolata
      - ttf-roboto
      - terminus-font
      - ttf-font-awesome
    state: present

- name: Install Arc Theme
  pacman:
    name:
      - arc-gtk-theme
      - gtk-engine-murrine
      - gnome-themes-extra
    state: present

- name: Install utilities
  pacman:
    name:
      - rxvt-unicode
      - xsel
      - rofi
      - conky
      - dmenu
      - urxvt-perls
      - perl-anyevent-i3
      - perl-json-xs
      - xsettingsd
      - lxappearance
      - feh
      - xclip
      - thunar
      - gvfs
      - thunar-volman

- name: Copy gtk2.0 theme
  copy:
    src: gtkrc-2.0
    dest: /home/vagrant/.gtkrc-2.0
    owner: vagrant
    group: vagrant
    mode: '0644'

- name: Ensures urxvt config dir exists
  file:
    path: /home/vagrant/.urxvt/ext
    state: directory
    owner: vagrant
    group: vagrant

- name: Copy urxvt configuration
  copy: src={{ item.src }} dest={{ item.dest }} owner=vagrant group=vagrant mode='0755'
  with_items:
    - { src: 'urxvt/ext/clipboard', dest: '/home/vagrant/.urxvt/ext/clipboard' }
    - { src: 'urxvt/ext/keyboard-select', dest: '/home/vagrant/.urxvt/ext/keyboard-select' }
    - { src: 'urxvt/ext/url-select', dest: '/home/vagrant/.urxvt/ext/url-select' }

- name: Ensures i3 config dir exists
  file:
    path: /home/vagrant/.config/i3
    state: directory
    owner: vagrant
    group: vagrant

- name: Copy i3 configuration
  copy:
    src: i3/config
    dest: /home/vagrant/.config/i3/config
    owner: vagrant
    group: vagrant
    mode: '0644'

- name: Ensures i3status config dir exists
  file:
    path: /home/vagrant/.config/i3status
    state: directory
    owner: vagrant
    group: vagrant

- name: Copy i3 status bar configuration
  copy:
    src: i3status/config
    dest: /home/vagrant/.config/i3status/config
    owner: vagrant
    group: vagrant
    mode: '0644'

- name: Copy Xresources configuration
  copy:
    src: xresources
    dest: /home/vagrant/.Xresources
    owner: vagrant
    group: vagrant
    mode: '0644'

- name: Copy Xinit configuration
  copy:
    src: profile
    dest: /home/vagrant/.profile
    owner: vagrant
    group: vagrant
    mode: '0644'

- name: Ensures fonts config dir exists
  file:
    path: /home/vagrant/.fonts/icomoon
    state: directory
    owner: vagrant
    group: vagrant

- name: Copy custom font feather
  copy:
    src: fonts/feather.ttf
    dest: /home/vagrant/.fonts/icomoon/feather.ttf
    owner: vagrant
    group: vagrant
    mode: '0755'

- name: Ensures backgrounds directory exists
  file:
    path: /usr/share/backgrounds
    state: directory

- name: Copy wallpaper for lightdm
  copy:
    src: wallpaper.png
    dest: /usr/share/backgrounds/wallpaper.png
    mode: '0644'

- name: Copy user image for lightdm
  copy:
    src: archlinux-icon.svg
    dest: /usr/share/backgrounds/archlinux-icon.svg
    mode: '0644'

- name: Copy wallpaper
  copy:
    src: wallpaper.png
    dest: /home/vagrant/.wallpaper.png
    owner: vagrant
    group: vagrant
    mode: '0644'

- name: Copy wallpaper config
  copy:
    src: fehbg
    dest: /home/vagrant/.fehbg
    owner: vagrant
    group: vagrant
    mode: '0755'

- name: Copy LightDM config
  copy:
    src: lightdm-gtk-greeter.conf
    dest: /etc/lightdm/lightdm-gtk-greeter.conf
    owner: root
    group: root
    mode: '0644'

- name: Enable LightDM
  systemd:
    name: lightdm
    enabled: yes
