---

- name: Ensure aur directory exists for user
  become: yes
  become_user: vagrant
  file:
    path: /home/vagrant/aur
    state: directory

- name: Clone burpsuite AUR repo
  become: yes
  become_user: vagrant
  git:
    repo: https://aur.archlinux.org/burpsuite.git
    dest: /home/vagrant/aur/burpsuite

- name: Install burpsuite
  become: yes
  become_user: vagrant
  command: makepkg --noconfirm -si
  args:
    chdir: /home/vagrant/aur/burpsuite
