---

- name: Ensure aur directory exists for user
  become: yes
  become_user: vagrant
  file:
    path: /home/vagrant/aur
    state: directory

- name: Clone smbmap AUR repo
  become: yes
  become_user: vagrant
  git:
    repo: https://aur.archlinux.org/smbmap.git
    dest: /home/vagrant/aur/smbmap

- name: Install smbmap
  become: yes
  become_user: vagrant
  command: makepkg --noconfirm -si
  args:
    chdir: /home/vagrant/aur/smbmap
