---

- name: Installing docker
  pacman:
    name: docker
    state: present

- name: Installing docker-compose
  pacman:
    name: docker-compose
    state: present

- name: adding user vagrant to group docker
  user:
    name: vagrant
    groups: docker
    append: yes

- name: Enable and start docker
  service:
    name: docker.service
    enabled: yes
    state: stopped
