---

- hosts: all
  become: yes

  pre_tasks:
    - name: Update system
      pacman:
        update_cache: yes
        upgrade: yes

  roles:
    - expand-disk
    - base
    - locale # thank you John! :D
    - iptables
    - shell
    - asdf
    - dotfiles
    - xorg
    - gnome
    - yay
    - golang
    - nasm
    - gdb
    - firefox
    - google-chrome
    - intellij
    - vscode
    - docker
    - tfenv
    - ansible
    - openssh
    - openvpn
    - nmap
    - wireshark
    - proxychains
    - smbclient
    - filezilla
    - tmux
    - burpsuite
    - ghidra
    - seclists
